In [1]:
# https://codepen.io/barney-parker/pen/QjXOmv/
# https://freefrontend.com/css-timelines/

In [2]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_excel("input/sheet.xlsx", sheet_name='schedule')
data['Day'] = data["Day"].fillna(method='ffill')
data.head(10)

,Day,Part of day,Name,Surname,Type,Dur. (M),Dur. (A),Start,End
0,Monday,Morning,NaN,NaN,Organizers,15.0,0.0,09:15:00,09:30:00
1,Monday,NaN,Sophia,Economou,Spotlight,NaN,60.0,09:30:00,10:30:00
2,Monday,NaN,Patrick,Huembeli,Regular,NaN,35.0,10:30:00,11:05:00
3,Monday,NaN,NaN,NaN,break,30.0,0.0,11:05:00,11:35:00
4,Monday,NaN,George,Booth,Regular,NaN,35.0,11:35:00,12:10:00
5,Monday,NaN,Olivier,Gauthé,Regular,NaN,35.0,12:10:00,12:45:00
6,Monday,NaN,NaN,NaN,break,90.0,0.0,12:45:00,14:15:00
7,Monday,Afternoon,Max,Welling,Spotlight,NaN,60.0,14:15:00,15:15:00
8,Monday,NaN,Atilla,Szabó,Regular,NaN,35.0,15:15:00,15:50:00
9,Monday,NaN,NaN,NaN,break,30.0,0.0,15:50:00,16:20:00

In [4]:
# def make_talk_html(start_time, end_time, first_name, last_name, title, abstract=None):
#     print(start_time)
#     block = """
#     <li class="event" data-date="{start_time} - {end_time}">
#       <div class="member-infos">
#         <h1 class='member-title'>{first_name} {last_name}</h1>
#         <h2 class="member-location ">Title: {title}</h2>
#       </div>
#     </li>
#     """.format(
#         start_time=start_time.strftime('%H:%M'),
#         end_time=end_time.strftime('%H:%M'),
#         title=title,
#         first_name=first_name,
#         last_name=last_name
#     )
#     return block

# def make_other_html(start_time, end_time, title):
#     block = """
#     <li class="event" data-date="{start_time} - {end_time}">
#       <div class="member-infos">
#         <h1 class='member-title'>{title}</h1>
#       </div>
#     </li>
#     """.format(
#         start_time=start_time.strftime('%H:%M'),
#         end_time=end_time.strftime('%H:%M'),
#         title=title,
#     )
#     return block

In [5]:
def make_talk_html(start_time, end_time, first_name, last_name, title, talk_type):
#     print(start_time)
    delta = {
        "Spotlight" : "45+15",
        "Regular"   : "25+10",
        "Short"     : "15+5"
    }[talk_type]
#     block = (
#         f"{start_time.strftime('%H:%M')} - {end_time.strftime('%H:%M')} ({delta})\n" +
#         f"    \n" +
#         f"        {first_name} {last_name}: {title}\n\n\n"
#     )
    name = f"{first_name} {last_name}"
    block = (
        f"{start_time.strftime('%H:%M')} - {end_time.strftime('%H:%M')} ({delta:5})"+
        f"\n{name:19}: {title}\n\n"
    )
    return block

def make_other_html(start_time, end_time, title):
    block = (
        f"{start_time.strftime('%H:%M')} - {end_time.strftime('%H:%M')}: {title.upper()}\n\n"
    )
    return block

In [6]:
from collections import defaultdict
html_blocks = defaultdict(list)

for day, df in data.groupby("Day"):
    
    df["Start"] = pd.to_datetime(df["Start"].astype(str).apply(pd.Timestamp))
    df["End"] = pd.to_datetime(df["End"].astype(str).apply(pd.Timestamp))
    df = df.sort_values(by="Start")
    
    for _, row in df.iterrows():
        #print(row)
        start_time = row.Start
        end_time = row.End
        day = row.Day
        #print(row.Name)  
        if not isinstance(row.Type, str):
            #print("Skip row")
            continue
        
        if row.Type in ('Spotlight', 'Regular', 'Short'):
#             print("Create one")
            first_name = row.Name
            last_name = row.Surname
            title = "TBD"
            code = make_talk_html(start_time, end_time, first_name, last_name, title, row.Type)
            html_blocks[day].append(code)

        else:
            title = row.Type
            code = make_other_html(start_time, end_time, title)
            html_blocks[day].append(code)
            
html_blocks = dict(html_blocks)
print(list(html_blocks.keys()));

['Friday', 'Monday', 'Thursday', 'Tuesday', 'Wednesday']

In [7]:
html_blocks["Monday"][-1]

'16:40 - 17:15 (25+10)\nYusuke Nomura      : TBD\n\n'

In [8]:
# with open("html_header.html", 'r') as f:
#     html_header = f.readlines()
#     html_header = "".join(html_header)
# with open("html_footer.html", 'r') as f:
#     html_footer = f.readlines()
#     html_footer = "".join(html_footer)
# with open("css_header.txt", 'r') as f:
#     css_header = f.readlines()
#     css_header = ["<style type=\"text/css\">\n"] + css_header + ["\n</style>\n"] 
#     css_header = css_header 
#     css_header = "".join(css_header)
    
# html_code = "".join(html_blocks["Monday"])
# # html_code = html_blocks["Monday"][1]
# html_code

In [11]:
days = ("Monday", "Tuesday", "Wednesday", "Thursday", "Friday")

html_code = ""
for day in days:
    v = html_blocks[day]
    html_code += f"\n{day.upper()}\n\n"
    html_code += "".join(v)
# html_code = html_blocks["Monday"][1]
html_code

"\nMONDAY\n\n09:15 - 09:30: ORGANIZERS\n\n09:30 - 10:30 (45+15)\nSophia Economou    : TBD\n\n10:30 - 11:05 (25+10)\nPatrick Huembeli   : TBD\n\n11:05 - 11:35: BREAK\n\n11:35 - 12:10 (25+10)\nGeorge Booth       : TBD\n\n12:10 - 12:45 (25+10)\nOlivier Gauthé     : TBD\n\n12:45 - 14:15: BREAK\n\n14:15 - 15:15 (45+15)\nMax Welling        : TBD\n\n15:15 - 15:50 (25+10)\nAtilla Szabó       : TBD\n\n15:50 - 16:20: BREAK\n\n16:20 - 16:40 (15+5 )\nGiulia Mazzola     : TBD\n\n16:40 - 17:15 (25+10)\nYusuke Nomura      : TBD\n\n\nTUESDAY\n\n09:15 - 09:50 (25+10)\nMartin Kliesch     : TBD\n\n09:50 - 10:25 (25+10)\nMarkus  Schmitt    : TBD\n\n10:25 - 10:55: BREAK\n\n10:55 - 11:30 (25+10)\nChristian Kokail   : TBD\n\n11:30 - 12:05 (25+10)\nEnrico Rinaldi     : TBD\n\n12:05 - 13:25: BREAK\n\n13:25 - 14:25 (45+15)\nTess Schmidt       : TBD\n\n14:25 - 14:45 (15+5 )\nPaolo Stornati     : TBD\n\n14:45 - 15:00: BREAK\n\n15:00 - 15:35 (25+10)\nStephen Clark      : TBD\n\n15:35 - 17:35: UNCONFERENCE\n\n\nWEDNESDAY\n\n09:15 - 10:15 (45+15)\nMatoshi Imada      : TBD\n\n10:15 - 10:50 (25+10)\nMartin Gärttner    : TBD\n\n10:50 - 11:20: BREAK\n\n11:20 - 11:55 (25+10)\nJuan Carasquilla   : TBD\n\n11:55 - 12:30 (25+10)\nMichele Grossi     : TBD\n\n12:30 - 14:00: BREAK\n\n14:00 - 15:00 (45+15)\nTitus Neupert      : TBD\n\n15:00 - 15:35 (25+10)\nPauline Ollitraut  : TBD\n\n15:35 - 16:05: BREAK\n\n16:05 - 16:40 (25+10)\nTom  O'Brien       : TBD\n\n16:40 - 17:15 (25+10)\nGuglielmo Mazzola  : TBD\n\n\nTHURSDAY\n\n09:15 - 09:50 (25+10)\nAlba Cervera-Lierta: TBD\n\n09:50 - 10:25 (25+10)\nNoboyuki Yoshio    : TBD\n\n10:25 - 10:55: BREAK\n\n10:55 - 11:30 (25+10)\nBalint Koczor      : TBD\n\n11:30 - 12:05 (25+10)\nJiahao Yao         : TBD\n\n12:05 - 12:40 (25+10)\nIrene López Gutiérrez: TBD\n\n12:40 - 14:00: BREAK\n\n14:00 - 14:35 (25+10)\nMarton Kanaszn     : TBD\n\n14:35 - 15:10 (25+10)\nFederico Becca     : TBD\n\n15:10 - 15:25: BREAK\n\n15:25 - 17:25: POSTERS\n\n\nFRIDAY\n\n09:15 - 09:50 (25+10)\nEd Barnes          : TBD\n\n09:50 - 10:25 (25+10)\nAnton Nykänen      : TBD\n\n10:25 - 10:40: BREAK\n\n10:40 - 11:00 (15+5 )\nTom Vieijra        : TBD\n\n11:00 - 11:20 (15+5 )\nGianluca Anselmetti: TBD\n\n11:20 - 11:35: BREAK\n\n11:35 - 12:10 (25+10)\nTyson Jones        : TBD\n\n12:10 - 12:30 (15+5 )\nDamian Hofmann     : TBD\n\n12:30 - 13:05 (25+10)\nAlessandro Lovato  : TBD\n\n"

In [12]:
with open("output.html", 'w') as f:
#     code = (css_header, html_header, html_code, html_footer)
    code = (html_code,)
    code = "\n".join(code)
    f.write(code)